server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root

mybatis-plus:
  global-config:
    db-config:
      #MP通过前缀识别表名
      table-prefix: tbl_
      #主键生成策略 auto代表自增
      id-type: auto
      #MP开启日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

